clone:
  git:
    image: plugins/git
    depth: 50
    tags: true

cache: [".npm"]

pipeline:
  npm-install:
    group: install
    image: node:8-alpine
    commands: ["npm install"]

  # Disabled because it uses a different eslint config file
  # eslint:
  #   group: test
  #   image: marcbachmann/eslint:5.2.0
  #   secrets: [gh_token]

  # Disabled because phantomJS does not run on DroneCI at the moment
  # test:
  #   group: test
  #   image: node:8-alpine
  #   commands: ["npm test -s"]

  publish:
    image: marcbachmann/semantic-release:15.1.3
    secrets: [gh_token, npm_token]
    when:
      event: push

  publish-gh-pages:
    image: plugins/gh-pages
    pages_directory: examples/
    username: x-oauth-basic
    secrets: [github_token]
    when:
      event: tag
